// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cumulative_te
NumericMatrix cumulative_te(NumericVector r, LogicalVector t, NumericVector x, int min_tc);
RcppExport SEXP _subgroupTree_cumulative_te(SEXP rSEXP, SEXP tSEXP, SEXP xSEXP, SEXP min_tcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type min_tc(min_tcSEXP);
    rcpp_result_gen = Rcpp::wrap(cumulative_te(r, t, x, min_tc));
    return rcpp_result_gen;
END_RCPP
}
// cumulative_tscore
NumericMatrix cumulative_tscore(NumericVector r, LogicalVector t, NumericVector x, double ate, int minbucket);
RcppExport SEXP _subgroupTree_cumulative_tscore(SEXP rSEXP, SEXP tSEXP, SEXP xSEXP, SEXP ateSEXP, SEXP minbucketSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ate(ateSEXP);
    Rcpp::traits::input_parameter< int >::type minbucket(minbucketSEXP);
    rcpp_result_gen = Rcpp::wrap(cumulative_tscore(r, t, x, ate, minbucket));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subgroupTree_cumulative_te", (DL_FUNC) &_subgroupTree_cumulative_te, 4},
    {"_subgroupTree_cumulative_tscore", (DL_FUNC) &_subgroupTree_cumulative_tscore, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_subgroupTree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
